vfs: Convert fs/vfs/vfs_bio.c -> fs/vfs/vfs_bio.cc
Drop unsued variable:

/home/asias/src/cloudius-systems/osv/fs/vfs/vfs_bio.cc: In function ‘int
bread(device*, int, buf**)’:
/home/asias/src/cloudius-systems/osv/fs/vfs/vfs_bio.cc:245:9: error:
variable ‘size’ set but not used [-Werror=unused-but-set-variable]
  size_t size;
         ^
/home/asias/src/cloudius-systems/osv/fs/vfs/vfs_bio.cc: In function ‘int
bwrite(buf*)’:
/home/asias/src/cloudius-systems/osv/fs/vfs/vfs_bio.cc:277:9: error:
variable ‘size’ set but not used [-Werror=unused-but-set-variable]
  size_t size;

Signed-off-by: Asias He <asias@cloudius-systems.com>